apiVersion: v1
kind: ConfigMap
metadata:
  name: zot-config
  namespace: zot
data:
  config.yaml: |
    http:
      address: 0.0.0.0
      port: "5000"
      compat: ["docker2s2"]

    storage:
      rootDirectory: /var/lib/zot
      dedupe: true

    log:
      level: debug

    extensions:
      search:
        enable: true
      ui:
        enable: true
