apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: observability
data:
  grafana.ini: |
    [server]
    domain = grafana.shaheen.homes
    root_url = https://grafana.shaheen.homes
    protocol = http
    enforce_domain = true

    [security]
    admin_user = admin
    admin_password = admin
    cookie_secure = true
    cookie_samesite = none

    [users]
    allow_sign_up = false
